### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/gammu#1]
Let me know when you're done with this package. Then I'll do a little code review and publish it on packagist.

**Comment by kristiandrucker** [comment]
@freekmurze I tested my code. It works. @matriphe please test your code if it works.

**Comment by freekmurze** [comment]
I've registered the package on packagist and started the external services. 

I'm leaving for a holiday soon and cannot guarantee I can do a review before that. @mpociot can you take care of the code review?
